Ais omar patch 1
brown-ccv/honeycomb-docs pull request #13
Opened 2022-08-04 00:33 UTC by AisOmar

Additional information added to version control documentation for the git workshop

2022-08-05 18:14 UTC, mirestrepo requested changes
This is great! And the images are super nice and helpful. Id' tweak the git commands to match the feature branch workflow and make sure that are also in synch with what @RobertGemmaJr does on the examples he added

2022-08-05 18:14 UTC, mirestrepo commented on docs/version_control.md
> +| git checkout &lt;branch&gt;   | checkout the branch you want to use                                |
You can do those two steps in on `git checkout -b <branch-name> ` Maybe worth mentioning?

But also the instructions from @RobertGemmaJr  should match this. I think if we use `switch` and `checkout` for the same operation we may confuse them unless we explicitly mention that there are different commands that do the same thing

2022-08-05 18:14 UTC, mirestrepo commented on docs/version_control.md
> +### Alternative options
I think this content is best before the ## Best Procatices section

Maybe in best practices we have an explicit explanation about workflow

I'll put a suggestion below

2022-08-05 18:14 UTC, mirestrepo commented on docs/version_control.md
> +
```suggestion
 ### Git Workflow
  
 We recommend using a simple flow based on following rules:

- Use topic/feature branches, no direct commits on main.
- Perform tests and code reviews before merges into main, not afterwards.
- Everyone starts from main, and targets main.
- Commit messages reflect intent.

**Branches**

* `main` is the default branch and where releases are made off. This branch should be in clean/working conditions at all times. This branch is protected and can only be merged from Pull Requests for topic branches
* `topic` branches are created for new features, fixes, or really any changes. E.g, `fix-task-trial2-stuck-button`

This flow is sometimes referred to as [Feature Branch Workflow](https://docs.gitlab.com/ee/gitlab-basics/feature_branch_workflow.html)
```

2022-08-05 18:48 UTC, RobertGemmaJr commented on docs/version_control.md
> +| git checkout &lt;branch&gt;   | checkout the branch you want to use                                |
Yeah I can make my changes to `git checkout -b`! No problem

2022-08-05 18:58 UTC, gtdang approved these changes
Looks good to me!

2022-08-05 20:37 UTC, hollandjg reviewed
I think we might want to shift the focus of the `version_control.md` somewhat – the first paragraph is great, but then it gets pretty technical, pretty quickly. 

The more technical stuff (hashes, etc.) we can probably leave out, and just point people to https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control 

Could we include an explicit quote from the git book:

If you are a psychology researcher and want to keep every version of an experiment ... 
> ... (which you would most certainly want to), a Version Control System (VCS) is a very wise thing to use. It allows you to revert selected files back to a previous state, revert the entire project back to a previous state, compare changes over time, see who last modified something that might be causing a problem, who introduced an issue and when, and more. Using a VCS also generally means that if you screw things up or lose files, you can easily recover. In addition, you get all this for very little overhead.
>
> https://git-scm.com/book/en/v2/Getting-Started-About-Version-Control

I'd want to include these topics right at the top:
- When you "commit", you create a saved version of your files which you can always go back to. (Might be good here to have a diagram of commits in a chain, with some branches pointing to the commits.)
- Life is easiest when you make a new "commit" every time you've made a small change to the code. An experienced coder might make tens of very small commits per hour. 
- A "branch" is a special saved version with a name, representing for instance the "main" version of your files, or a new version with a new or changed functionality or feature. 
- You will always be "on a branch" in git, that is to say that when you're not working on a new feature you will be "on the main branch", viewing a version of the code without any partial changes, and when you're working on a new feature you should be "on a feature branch" which might have partial changes towards some goal. 
- When you think you're done with a new feature, you can create a "pull request", which allows your collaborators to review the the new files before you finish the feature by updating the "main" branch to include it. This process is called "merging".
- If you're unhappy with a new feature you've been working on, you can always start over by changing back to the "main" branch, creating a new "feature" branch, and starting again. But you can always go back to the discarded first version of the new feature if you want.
- It's easy and fast to create and delete branches, and you can always recover every intermediate version of the files which you have committed.
- You can also create duplicates of all your versions and branches by "pushing" them to GitHub. It's simple to keep the version on your computer and the version on GitHub in sync by "pushing" new changes you've made and "pulling" changes which have been made on GitHub directly (or pushed there by other people).

Do we want to make the default interaction with git via the GUI or via the command line? I'd probably go for the GUI for the workshop as then you don't have any trouble with API keys. That might be best to put at the top of the file.

2022-08-05 20:37 UTC, hollandjg commented on docs/quick_start.md
>  The simplest way to get started is creating a new repository using Honeycomb as a template.
This will only work if the user is signed in (and by extension also signed up)
```suggestion
The simplest way to get started is creating a new repository using Honeycomb as a template.

You will need to be signed into GitHub for the following steps to work. If you aren't, or you don't have an account, you can sign up and sign in at [github.com](https://www.github.com).
```

2022-08-05 20:37 UTC, hollandjg commented on docs/quick_start.md
> +![](assets/template.png)
This is looking better, but it might be worthwhile doing it one more time with an empty browser profile without tabs or bookmarks (like this in Chrome: 
<img width="318" alt="Screen Shot 2022-08-05 at 15 42 10" src="https://user-images.githubusercontent.com/2803227/183149465-2d493e0b-78b8-43a2-ac37-73a4e5317b89.png">
)

2022-08-05 20:37 UTC, hollandjg commented on docs/version_control.md
> +### Alternative options
Might this section on the GUI be better put at the top? It's possibly much more intuitive for beginners. And should it be the main way we suggest people use the tools?

2022-08-05 20:37 UTC, hollandjg commented on docs/version_control.md
> +We encourage using [Commitizen](http://commitizen.github.io/cz-cli/), a great tool for writing angular commits - this will create a standardized commit format which makes for easier change logging an
I'm not sure what "angular" means here. Might we want to make it a bit more targeted at people who haven't used git before?: 
```suggestion
We encourage using [Commitizen](http://commitizen.github.io/cz-cli/), a great tool for recording descriptions of commits in a standardized format which makes it easier for people to understand what changed in the code.
```

2022-08-08 14:03 UTC, mirestrepo approved these changes

2022-08-08 14:04 UTC, mirestrepo commented on docs/version_control.md
> +### Alternative options
I'd be okay with that!

2022-08-08 14:45 UTC, RobertGemmaJr approved these changes
This is looking pretty great! A couple small things and general comments for all of us to think about but nothing that makes me feel the need to re-review it. Take a look and send it 🚀

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/quick_start.md
>  Alternatively, you can use GitHub CLI to create a new project based on the Honeycomb template repository. First, install GitHub CLI (https://cli.github.com/), then simply run on your terminal:
Looks like this was in the original markdown but "just", "simply", etc  shouldn't be in docs. Can invoke some imposters syndrome

```suggestion
Alternatively, you can use GitHub CLI to create a new project based on the Honeycomb template repository. First, install GitHub CLI (https://cli.github.com/), then run on your terminal: 
```

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/version_control.md
> +### Alternative options
I definitely think the GUI solution is something we should share briefly during the workshop. I know I do almost all of my commit/push/pull from VS Code and only touch the command line if I'm doing some more tricky stuff.

Imo so long as people have a grasp of what they (commit/push/pull) and what's happening when they use the gui it's safe to use and easier for beginners

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/version_control.md
> +- Perform tests and code reviews before merges into main, not afterwards.
Is there an action for running the tests on push? Perhaps we could make one and instruct the users to set up that action on top of firebase

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/version_control.md
> +- Perform tests and code reviews before merges into main, not afterwards.
cc @eldu

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/version_control.md
> +- Everyone starts from main, and targets main.
```suggestion
- Every branch starts from main, and targets main.
```

2022-08-08 14:45 UTC, RobertGemmaJr commented on docs/version_control.md
> +* `topic` branches are created for new features, fixes, or really any changes. E.g, `fix-task-trial2-stuck-button`
We should stick to either `-` or `*` for the bullet points, `-` seems to be much more common

2022-08-08 19:08 UTC, mirestrepo commented on docs/version_control.md
> +We encourage using [Commitizen](http://commitizen.github.io/cz-cli/), a great tool for writing angular commits - this will create a standardized commit format which makes for easier change logging an
Angular commits are also known as [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) - we could use that notation instead and set the link

2022-08-08 23:29 UTC, merged