docs: Docs 3.1 Prerequisites page
brown-ccv/honeycomb-docs pull request #70
Opened 2023-06-12 17:51 UTC by RobertGemmaJr

Updates the prerequisites page, builds off #68

- Page is now organized by OS (independent packages, then mac, then Windows
- Removes pyenv info for Windows
- Adds manual install links for Mac, Linux, and Windows

2023-06-12 17:52 UTC, RobertGemmaJr commented
Here's the full prerequisites page:

```
---
id: prerequisites
slug: /prerequisites
title: Prerequisites
description: Overview of prerequisite software and how to install them
---
```

It is important that your computer is set up with the necessary packages before you begin development. You will come across a variety of errors if these prerequisites are not installed. **The [quick start](quick_start#installing-prerequisites) guide explains how to run an automated install**, this page details what programs and packages are needed to run and build Honeycomb. There are some OS specific prerequisites needed to build a task as a desktop application.

## OS Independent

### Git

[git](https://git-scm.com) is an open source version control system. It is used to track changes, revert mistakes, and enable peer code reviews!

[GitHub Desktop](https://desktop.github.com) is a GUI application used to interact with git and GitHub directly from your computer. It is not strictly needed but many folks find it easier to work with then using git directly from the command line.

### Node JS

[NodeJS](https://nodejs.org/en) is a cross-platform runtime environment for JavaScript code. Almost every web application today builds on top of node.

Note Honeycomb needs version 16 or later to run - the installers run the long term support (LTS) version. This is version 18 as of June 2023

### Python

[Python](https://www.python.org) is a high-level programming language. Some "under the hood" tools needed by Honeycomb are written in python so it must be installed on your system.

Note Honeycomb needs version 3.7 or later to run - the installers use version 3.11.

### Oracle JDk

[Java](https://www.oracle.com/java/) is another high-level programming languages that some tools (Namely the Firebase Emulators) are written in. We must install a JDK (Java Development Kit) for it to run.

Note Honeycomb needs version 11 or later to run - the installers use version 18.

### Visual Studio Code

[Visual Studio Code](https://code.visualstudio.com) is a well-loved and easy to use integrated development environment (IDE). This is the program you'll use to write your task.

## Mac Specific Installs

### X-Code

[XCode](https://developer.apple.com/xcode/) is a special IDE for the Apple platform. It comes with everything needed to compile desktop applications from an Apple computer. It must be installed from the terminal:

```shell title="Installing XCode"
  xcode-select --install
```

### Rosetta

Rosetta is a translation layer built for Mac computers with Apple Silicon. It should ask to be installed if any of the prerequisite tools need it. Otherwise, [this guide](https://support.apple.com/en-us/HT211861) can be used to make sure it is on your apple silicon system.

## Windows Specific Install

### Visual Studio

[Visual Studio](https://visualstudio.microsoft.com) is a special IDE for the Windows platform. It comes with everything needed to compile desktop applications from a PC. Visual Studio Community is a free to use platform.

The "Desktop development with C++" workload must also be installed on your system. The automated installers will do so.

## Manual Installation (macOS)

- [Git](https://git-scm.com/download/mac)
- [GitHub Desktop](https://desktop.github.com)
- [Node.js](https://nodejs.org/en/download/)
  - We recommend installing the "LTS" option for better stability
- [Python](https://www.python.org/downloads/macos/)
- [Oracle JDK](https://www.oracle.com/java/technologies/downloads/#jdk20-windows)
- [VS Code](https://code.visualstudio.com/download)
- [Xcode](https://apps.apple.com/us/app/xcode/id497799835?mt=12)

## Manual Installation (Windows)

The links below will take you to each project installation page should you prefer to manually install the prerequisite software.

- [Git](https://git-scm.com/download/win)
- [GitHub Desktop](https://desktop.github.com)
- [Node.js](https://nodejs.org/en/download/)
  - We recommend installing the "LTS" option for better stability
- [Python](https://www.python.org/downloads/windows/)
- [Oracle JDK](https://www.oracle.com/java/technologies/downloads/#jdk20-mac)
- [VS Code](https://code.visualstudio.com/download)
- Visual Studio:
  - [Visual Studio 2022 Community](https://visualstudio.microsoft.com/vs/community/)
  - Install the [Native C++ Workflow](https://docs.microsoft.com/en-us/cpp/build/vscpp-step-0-installation?view=msvc-160#step-4---choose-workloads-1)

## Manual Installation (Linux)

The links below will take you to each project installation page should you prefer to manually install the prerequisite software. Your preferred installation method for the programs listed [above](#os-independent) should get you up and running on any Linux distro new enough to support GLIBC_2.28.

- [Git](https://git-scm.com/download/linux)
- [GitHub Desktop](https://desktop.github.com)
- [Node.js](https://nodejs.org/en/download/)
  - We recommend installing the "LTS" option for better stability
- [Python](https://www.python.org/downloads/source/)
- [Oracle JDK](https://www.oracle.com/java/technologies/downloads/#jdk20-linux)
- [VS Code](https://code.visualstudio.com/download)
- Install [Clang](https://clang.llvm.org/get_started.html) or follow installation instructions on the [electron docs](https://www.electronjs.org/docs/development/build-instructions-linux#prerequisites)
- Development headers of `GTK 3` and `libnotify` (Follow installation instructions on the [electron docs](https://www.electronjs.org/docs/development/build-instructions-linux#prerequisites))

## Further Help

If you are still having issues setting up your computer you can find the full instructions on the [electron documentation](https://www.electronjs.org/docs/development/build-instructions-gn) for your specific OS.

2023-06-13 13:07 UTC, tdivoll requested changes
Looking good, just some cleanups!

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +[git](https://git-scm.com) is an open source version control system. It is used to track changes, revert mistakes, and enable peer code reviews!
```suggestion
[git](https://git-scm.com) is an open-sourced version control system. It is used to track changes, revert mistakes, and enable peer code reviews!
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +[GitHub Desktop](https://desktop.github.com) is a GUI application used to interact with git and GitHub directly from your computer. It is not strictly needed but many folks find it easier to work wit
```suggestion
[GitHub Desktop](https://desktop.github.com) is a GUI application used to interact with git and GitHub directly from your computer. It is not strictly needed but many folks find it easier to work with than using git directly from the command line.
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +Note Honeycomb needs version 16 or later to run - the installers run the long term support (LTS) version. This is version 18 as of June 2023
```suggestion
:::note 
Honeycomb needs version 16 or later to run - the installers run the long term support (LTS) version. This is version 18 as of June 2023
:::
```
Will this note syntax work here? And in the other notes below?

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +[Java](https://www.oracle.com/java/) is another high-level programming languages that some tools (Namely the Firebase Emulators) are written in. We must install a JDK (Java Development Kit) for it to
```suggestion
[Java](https://www.oracle.com/java/) is another high-level programming languages that some tools  are written in (namely, the Firebase Emulators). We must install a JDK (Java Development Kit) for it to run.
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +## Mac Specific Installs
```suggestion
## Mac-specific Installs
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +Rosetta is a translation layer built for Mac computers with Apple Silicon. It should ask to be installed if any of the prerequisite tools need it. Otherwise, [this guide](https://support.apple.com/en
```suggestion
Rosetta is a translation layer built for Mac computers with Apple Silicon. It should ask to be installed if any of the prerequisite tools need it. Otherwise, [this guide](https://support.apple.com/en-us/HT211861) can be used to make sure it is on your Apple silicon system.
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +## Windows Specific Install
```suggestion
## Windows-specific Install
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +The "Desktop development with C++" workload must also be installed on your system. The automated installers will do so.
Is this a box that gets checked during Visual Studio install? Maybe make it clear that it is an option within Visual Studio that is required for Honeycomb workflows.

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +## Manual Installation (macOS)
```suggestion
## Manual Installation (macOS)

The links below will take you to each project installation page should you prefer to manually install the prerequisite software.
```

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +Note Honeycomb needs version 3.7 or later to run - the installers use version 3.11.
Wrap this in :::note:::

2023-06-13 13:07 UTC, tdivoll commented on docs/prerequisites.mdx
> +Note Honeycomb needs version 11 or later to run - the installers use version 18.
Wrap in :::note:::

2023-06-13 13:07 UTC, tdivoll commented on docs/quick_start.mdx
>  1. Run Powershell as an admin form the start menu
```suggestion
1. Run Powershell as an admin from the start menu

```

2023-06-13 13:07 UTC, tdivoll commented on docs/quick_start.mdx
>     ![Powershell admin launcher](assets/powershell_admin.png)
Line 93 - Pase should be Paste

2023-06-13 13:07 UTC, tdivoll commented on docs/quick_start.mdx
>     ![Powershell admin launcher](assets/powershell_admin.png)
Same on line 119

2023-06-13 13:56 UTC, RobertGemmaJr commented on docs/prerequisites.mdx
> +The "Desktop development with C++" workload must also be installed on your system. The automated installers will do so.
The installers are set to check the box by default but they do have to click approve

2023-06-13 13:59 UTC, RobertGemmaJr commented on docs/prerequisites.mdx
> +Note Honeycomb needs version 16 or later to run - the installers run the long term support (LTS) version. This is version 18 as of June 2023
Done! I switched it for every instance

2023-06-13 14:02 UTC, RobertGemmaJr commented on docs/prerequisites.mdx
> +The "Desktop development with C++" workload must also be installed on your system. The automated installers will do so.
Changed the wording a little, I also make it more explicit in the quick start guide that it's a prompt as part of the Visual Studio installl

2023-06-13 19:33 UTC, tdivoll approved these changes
Looks good Rob!

2023-06-14 15:08 UTC, merged